plugins {
    id 'com.android.application'
}

android {
    namespace 'com.tilbuci.showtime'
    compileSdk 34

    defaultConfig {
        applicationId "com.tilbuci.showtime"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.9.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'org.nanohttpd:nanohttpd:2.3.1' // For local web server
    implementation 'com.github.mik3y:usb-serial-for-android:3.4.6'
}