ALTER TABLE scenes ADD COLUMN sc_dflow1 TEXT NOT NULL DEFAULT '';
ALTER TABLE scenes ADD COLUMN sc_dflow2 TEXT NOT NULL DEFAULT '';
ALTER TABLE scenes ADD COLUMN sc_dflow3 TEXT NOT NULL DEFAULT '';
ALTER TABLE scenes ADD COLUMN sc_dflow4 TEXT NOT NULL DEFAULT '';
INSERT OR REPLACE INTO config (cf_key, cf_value) VALUES ('dbVersion', '17');